### ISSUE TITLE
Add a keyboard shortcut to take a screen capture.

### ISSUE THREAD

**Issue by bobifle** [JamzTheMan/TokenTool#14]
CTRL +

z, x, c, v, q,s,d,f,a,z,e,r

are good candidates, you can keep your right hand on your mouse.

**Comment by Phergus** [comment]
Most if not all of those are already used.

Export -> Screenshot already has Ctrl-Shift-S

And of course, Alt-PrtScrn, on Windows produces a screenshot of the MT window.

**Comment by bobifle** [comment]
Are we talking about the same thing ? I only see 2 shortcuts in tokentool 2.0

**Comment by JamzTheMan** [comment]
Me thinks @Phergus has MapTool on the brain?

**Comment by JamzTheMan** [comment]
Ctrl+x/c/v are usually cut/copy/paste so bad candidates... s is usually save (well, menu option save) 

I think I'll go with ctrl+r  (dunno, region capture? in my head it makes sense)  A little far for Left handed mousers but that's not a requirement :)

**Comment by Phergus** [comment]
Yup.  Was thinking MapTool.  Sorry

**Comment by JamzTheMan** [comment]
Accelerator added.  I also added accelerators for other menu options and changed the Copy/Paste to properly use OS specific shortcut key (control/command). Copy/Paste was also using "Control then C/P" vs "Control+C/P" which is why the old meny just showed a C or P vs Ctrl+C/P.

TIL about FXML accelerators... 

![tokentool accelerators added](https://user-images.githubusercontent.com/8051654/42288956-a90a446c-7f82-11e8-9666-bb48b11457fd.png)

**Comment by bobifle** [comment]
If I'm not too late in the game : CTRL+s to save a file ? 
Edit: I've seen you've already done that... great job !
